uav_names: [
  "uav10",
]

frames:
  fcu:
    publish_tf: false

uav10:

  frame: "x500"
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0.0

mrs_uav_flightforge_simulator:

  sensors:

    lidar:

      enabled: true

    rgb:

      rate: 30 # [Hz]

      enabled: true
      offset_x: 5.0 # [m]
      offset_y: 0.0 # [m]
      offset_z: -0.9 # [m]

      rgb_segmented:
        enabled: false
        rate: 10.0 # [Hz]

      depth:
        enabled: false

    stereo:
      enabled: false

  graphics_settings: "medium"

  realtime_factor: 1.0 # [-]

  # world_name: "valley" # works in Lite
  # world_name: "warehouse" # works in Lite

  # TODO
  # world_name: "cave" # does not work
  # world_name: "dead_spruce_forest" # does not work
  # world_name: "infinite_forest" # does not work
  world_name: "forest" # does not work

  # weather_type: "cloudy"

  daytime:

    hour: 15
    minute: 30
