<?xml version="1.0"?>
<package format="3">
  <name>monodepth_navigation</name>
  <version>0.1.0</version>
  <description>The ros2 monodepth_navigation package</description>


  <maintainer email="tom@todo.todo">tom</maintainer>

  <license>TODO</license>


  <!-- build system -->
  <buildtool_depend>ament_python</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- runtime -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>


</package>
