uav_names: [
  "uav1",
]

uav1:
  frame: "a300"
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0.0

world_name:
  "service_tunnel"

weather_type:
  "sunny"

sensors:

  rgb:
    enabled: true

    rate: 30.0 # [Hz]

    width: 800 # [px]
    height: 800 # [px]
    fov: 120.0 # [deg]

    offset_x: 0.14 # [m]
    offset_y: 0.0 # [m]
    offset_z: 0.0 # [m]

    rotation_pitch: 30.0 # [deg]
    rotation_yaw: 0.0 # [deg]
    rotation_roll: 0.0 # [deg]

  stereo:
    width: 672 # [px]
    height: 384 # [px]
    enabled: true
    rotation_pitch: 0.0
    rotation_yaw: 0.0

  lidar:
    enabled: true
    horizontal_rays: 128 # [-]
    vertical_rays: 32 # [-]
    offset_x: 0.2 # [m]
    offset_y: 0.0 # [m]
    offset_z: -0.1 # [m]
    rotation_pitch: 30.0 # [deg]
    rotation_roll: 0.0 # [deg]
    rotation_yaw: 0.0 # [deg]
    lidar_segmented:
      enabled: false 
      rate: 10.0 # [Hz]

