mrs_octomap_server:

  octomap_server:

    resolution: &voxel_res 0.25 # [m]

    sensor_model:
      hit: 0.62
      miss: 0.45
      min: 0.12
      max: 0.90

    # for point cloud raycasting
    sensor_params:

      3d_lidar:
        n_sensors: 1

        sensor_0:

          max_range: 240 # [m] max range of points to be included as occupied
          free_ray_distance: 10.0 # [m] max distance for free space raycasting

          vertical_fov_angle: 1.57 # [rad]

          horizontal_rays: 128 # [-]
          vertical_rays: 64 # [-]

          unknown_rays:
#            update_free_space: true
            update_free_space: false
#            clear_occupied: true
            clear_occupied: false
            free_ray_distance_unknown: 10.0

          decimation:
            enabled: true
            voxel_size: *voxel_res # [m]

          crop_robot_body:
            enabled: true
            box_size: 1.5 # [m]

      depth_camera:
        n_sensors: 0

mrs_octomap_planner:

  octomap_planner:

    planning_tree:

      resolution: *voxel_res

    distance_transform:
      submap_distance: 240.0 # [m] from the UAV into all directions

    main_timer:
      rate: 3.0 # [Hz]

    diagnostics_timer:
      rate: 10.0 # [Hz]

    safe_obstacle_distance:
      default: 1.0 # [m]
      min: 0.8 # [m]
      max: 5.0 # [m]

    subt_planner:
      use: true