uav_names: [
  "uav1",
]

frames:
  fcu:
    publish_tf: false

uav1:
  frame: "x500"
  type: "x500"
  spawn:
    x: -30.0
    y: 0.0
    z: 0.0
    heading: 0.0


mrs_uav_flightforge_simulator:

  sensors:

    lidar:

      enabled: true

    rgb:

      rate: 30 # [Hz]

      enabled: true
      offset_x: 5.0 # [m]
      offset_y: 0.0 # [m]
      offset_z: -0.9 # [m]

      rotation:
#        pitch: 45.0 # [deg]
        pitch: 0.0 # [deg]
        roll: 0.0 # [deg]
        yaw: 0.0 # [deg]

      rgb_segmented:
        enabled: false
        rate: 10.0 # [Hz]

      depth:
        enabled: false

    stereo:
      enabled: false

  graphics_settings: "low"
#  graphics_settings: "medium"
#  graphics_settings: "high"

  realtime_factor: 1.0 # [-]


  world_name: "forest"
#  world_name: "service_tunnel"
#  world_name: "cave"
#  world_name: "eletric_towers"

  daytime:

    hour: 15
    minute: 30

  # Choose cluttered difficulties from 1 [high] to 10 [low]
  ueds_forest_density: 10

  # Choose Hilly Level from 1 [totally flat] to 5 [the most hilly]
  ueds_forest_hilly_level: 2

